language: ruby
sudo: false
dist: trusty
cache: bundler
rvm:
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - jruby-head
  - ruby-head
  - rbx-3
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: rbx-3
